import "./globals.css";
import Image from "next/image";
import {Kanit} from "@next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const kanit = Kanit({
  weight:'400',
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`select-none ${kanit.className}`}>
      <body>
        <div className="h-full w-full bg-hero bg-no-repeat bg-fixed bg-cover">
          <div className="bg-black w-full h-full lg:bg-opacity-50">       
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
